### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by fpon** [fpon/protospace-34800#1]
https://protospace-34800.herokuapp.com/

**Comment by commy0416** [comment]
確認しました。
下記の修正点がございます。

コメントを複数回した時に、コメントが横並びではなく縦並びになるようにしてください

修正が完了しましたら、再度フォームからご提出をお願い致します

**Comment by fpon** [comment]
変更しました！
ご確認よろしくお願いします

**Comment by checker-ms** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が引き続き見受けられましたので修正をお願いします！

[現状]
①フォームを空のまま投稿しようとすると、投稿できずにエラーページが表示されてしまう
②ログイン状態で、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックしても、編集ページへ遷移できない（トップページに遷移してしまう）
③ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページに、そのユーザーが投稿したプロトタイプが表示されていない

[修正箇所]
①フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること
②ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できること
③ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by fpon** [comment]
ご確認ありがとうございます。
問題点２、３は変更しました。
問題点１なのですが、空だとプロトタイプが投稿できずエラーになるとのことでしたが
自分の画面ではエラーが出てこず正常に動作しているので、どこを直せば良いのかわからなかったです
２、３は修正したのでご確認よろしくお願いします

**Comment by checker-ms** [comment]
ご提出ありがとうございます！
問題点２、３については修正確認できました！
問題点１については、メンターへの質問はお済みでしょうか？

もしお済みでなければ、一度ご相談いただけたらと思います。

**Comment by fpon** [comment]
度々ご確認していただきありがとうございます！
問題１の変更をしたので確認よろしくお願いします！

**Comment by checker-ms** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
